name: Bug Report | Bug 报告
description: Create a Bug Report | 创建一个 Bug 报告
title: "[Bug] "
labels: ["bug", "pending"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description | 问题描述
      description: Please describe the issue in detail | 请详细描述这个问题
      placeholder: Describe your issue here | 在这里描述你的问题
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps | 复现步骤
      description: How to reproduce this issue | 如何重现这个问题
      placeholder: 这里写你的复现步骤
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior | 预期行为
      description: Optional - what you expect to happen | 可选 - 你认为预期应该是怎么样的
      placeholder: Describe the expected behavior here | 这里写你认为预期是怎么样的
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior | 实际行为
      description: What actually happened | 实际操作时是怎么样的
      placeholder: Describe the actual behavior here | 这里写你的实际操作时是怎么样的
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 环境

  - type: input
    id: os
    attributes:
      label: Operating System | 操作系统
      description: For example, Windows 11, macOS 14, Ubuntu 22.04, etc. | 例如，Windows 11、macOS 14、Ubuntu 22.04 等
      placeholder: For example, windows11 | 例如，Windows 11
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Software Version | 软件版本
      description: For example, 0.6.5 or the latest dev branch | 例如，0.6.5 或最新 dev 分支
      placeholder: For example, 0.6.5 or the latest dev branch | 例如，0.6.5 或最新 dev 分支
    validations:
      required: true

  - type: textarea
    id: other-env
    attributes:
      label: Other Environment Information | 其他环境信息
      description: Optional - for example, Java version, Minecraft version, etc. | 可选 - 例如 Java 版本、Minecraft 版本等
      placeholder: Optional - for example, Java version, Minecraft version, etc. | 可选 - 例如 Java 版本、Minecraft 版本等
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots (if any) | 日志或截图（如果存在）
      description: Paste the log file upload URL, or upload an image | 粘贴日志文件上传地址，或是上传图片
      placeholder: Paste your log file upload URL, or upload an image | 这里粘贴你的日志文件上传地址，或是上传图片
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes | 其他信息
      description: Optional - additional information, ignore if not applicable | 可选 - 其他信息，如果没有请忽略
      placeholder: Additional information, ignore if not applicable | 其他信息，如果没有请忽略
    validations:
      required: false
