name: Improvement Request | 优化请求
description: Request to improve content | 请求优化内容
title: "[Perf] "
labels: ["performance", "pending"]
assignees: []
body:
  - type: textarea
    id: content
    attributes:
      label: 内容描述
      description: What content needs improvement? | 需要优化的内容是什么？
      placeholder: What content needs improvement? | 需要优化的内容是什么？
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由
      description: Explain why you want to improve this content | 说明你为什么想要优化这个内容
      placeholder: Explain why you want to improve this content | 说明你为什么想要优化这个内容
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 影响
      description: Explain the impact of the improvement | 说明优化的影响
      placeholder: Explain the impact of the improvement | 说明优化的影响
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: Explain the acceptance criteria for the improvement | 说明优化的验收标准
      placeholder: Explain the acceptance criteria for the improvement | 说明优化的验收标准
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 附加内容
      description: Optional - for example, sketches of the interface | 可选 - 例如界面草图
      placeholder: Optional - for example, sketches of the interface | 可选 - 例如界面草图
    validations:
      required: false
