use std::collections::HashMap;
use std::path::Path;

use super::super::shared::read_server_port;

pub(super) fn ensure_server_properties_for_import(
    run_dir: &Path,
    requested_port: u16,
    online_mode: bool,
) -> Result<u16, String> {
    let server_properties_path = run_dir.join("server.properties");
    if server_properties_path.exists() {
        let port = read_server_port(run_dir, requested_port);
        let mut updates = HashMap::new();
        updates.insert("online-mode".to_string(), online_mode.to_string());
        crate::services::server::config::write_properties(
            server_properties_path.to_str().unwrap_or_default(),
            &updates,
        )
        .map_err(|e| format!("更新 server.properties 失败: {}", e))?;
        return Ok(port);
    }

    let content = format!(
        "# Minecraft server properties\n# Generated by SeaLantern\nserver-port={}\nonline-mode={}\n",
        requested_port, online_mode
    );
    std::fs::write(&server_properties_path, content)
        .map_err(|e| format!("创建 server.properties 失败: {}", e))?;

    Ok(requested_port)
}
