use std::path::Path;

use crate::hardcode_data::app_files::SERVER_PATH_PERMISSION_TEST_FILE_NAME;

pub(super) fn trim_optional_string(value: Option<&String>) -> Option<String> {
    value
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
}

pub(super) fn read_server_port(server_dir: &Path, fallback: u16) -> u16 {
    let server_properties_path = server_dir.join("server.properties");
    if !server_properties_path.exists() {
        return fallback;
    }

    if let Ok(props) = crate::services::server::config::read_properties(
        server_properties_path.to_str().unwrap_or_default(),
    ) {
        if let Some(port_str) = props.get("server-port") {
            if let Ok(parsed_port) = port_str.parse::<u16>() {
                println!("从 server.properties 读取端口: {}", parsed_port);
                return parsed_port;
            }
        }
    }

    fallback
}

pub(super) fn create_server_properties_if_missing(
    server_dir: &Path,
    requested_port: u16,
    online_mode: bool,
) -> Result<(), String> {
    let server_properties_path = server_dir.join("server.properties");
    if server_properties_path.exists() {
        return Ok(());
    }

    let content = format!(
        "# Minecraft server properties\n# Generated by SeaLantern\nserver-port={}\nonline-mode={}\n",
        requested_port, online_mode
    );
    std::fs::write(&server_properties_path, content)
        .map_err(|e| format!("创建 server.properties 失败: {}", e))?;

    println!("已创建 server.properties: {}", server_properties_path.display());
    Ok(())
}

/// 将启动内存设置写入服务器目录下的 SL.json。
///
/// 这是新建/导入服务器时持久化内存配置的主路径；ServerInstance 上的
/// max_memory/min_memory 仅作为历史数据兼容字段保留。
pub(super) fn write_sl_startup_config(
    server_dir: &Path,
    max_memory: u32,
    min_memory: u32,
) -> Result<(), String> {
    let config = crate::commands::server::config::SLStartupConfig {
        max_memory: Some(max_memory),
        min_memory: Some(min_memory),
    };
    let content =
        serde_json::to_string_pretty(&config).map_err(|e| format!("序列化 SL.json 失败: {}", e))?;
    let sl_path = server_dir.join("SL.json");
    std::fs::write(&sl_path, content).map_err(|e| format!("写入 SL.json 失败: {}", e))?;
    println!("已创建 SL.json: {}", sl_path.display());
    Ok(())
}

pub(super) fn ensure_server_path_writable(server_path: &Path) -> Result<(), String> {
    let test_file = server_path.join(SERVER_PATH_PERMISSION_TEST_FILE_NAME);
    if std::fs::write(&test_file, "").is_err() {
        return Err("无法写入服务器目录，请检查权限".to_string());
    }
    let _ = std::fs::remove_file(&test_file);
    Ok(())
}
